"""Trend view over all run records: evals/history/TREND.md and trend.html.

One row per record, ordered by point_time (time of the agent content). A
regression is flagged when, between consecutive points that both report a
layer, the layer score drops, or when a test id that passed at its previous
point now fails (in any repeat).

trend.html is a single static file (inline CSS/SVG, no external assets).
"""

from __future__ import annotations

import html
from pathlib import Path

from totto_suite import config, records


def _short(sha: str | None) -> str:
    return (sha or "")[:7]


def _aggregate(tests: list[dict]) -> dict[str, str]:
    """Per test id: PASS (all decided repeats pass), FAIL (all fail),
    FLAKY (mixed). Ids with only INFRA_ERROR/SKIPPED are left out."""
    by_id: dict[str, list[str]] = {}
    for t in tests:
        if t.get("status") in ("PASS", "FAIL"):
            by_id.setdefault(str(t["id"]), []).append(t["status"])
    out = {}
    for tid, sts in by_id.items():
        if all(s == "PASS" for s in sts):
            out[tid] = "PASS"
        elif all(s == "FAIL" for s in sts):
            out[tid] = "FAIL"
        else:
            out[tid] = "FLAKY"
    return out


def compute_regressions(recs: list[dict]) -> dict[str, list[dict]]:
    """Returns {run_id: [flag, ...]} for records sorted by point_time."""
    prev_layer: dict[str, tuple[str, float]] = {}
    prev_test: dict[str, tuple[str, str]] = {}
    flags: dict[str, list[dict]] = {}
    for r in recs:
        run_flags = []
        for layer, s in sorted(r.get("layers", {}).items()):
            score = s.get("score")
            if score is None:
                continue
            if layer in prev_layer and score < prev_layer[layer][1] - 1e-9:
                run_flags.append(
                    {
                        "type": "layer_score_drop",
                        "layer": layer,
                        "from": prev_layer[layer][1],
                        "to": score,
                        "previous_run": prev_layer[layer][0],
                    }
                )
            prev_layer[layer] = (r["run_id"], score)
        for tid, status in sorted(_aggregate(r.get("tests", [])).items()):
            prev = prev_test.get(tid)
            if prev and prev[1] == "PASS" and status in ("FAIL", "FLAKY"):
                run_flags.append(
                    {
                        "type": "test_pass_to_fail",
                        "test": tid,
                        "from": "PASS",
                        "to": status,
                        "previous_run": prev[0],
                    }
                )
            prev_test[tid] = (r["run_id"], status)
        flags[r["run_id"]] = run_flags
    return flags


def _version_cell(r: dict) -> str:
    c = r["cxas"]
    status = c.get("version_status")
    if c.get("version_id") and status in ("in_version_list", "hidden_fetchable"):
        return f"{c['version_id']} ({status})"
    return status or "?"


def _layer_cell(s: dict) -> str:
    score = s.get("score")
    pct = "n/a" if score is None else f"{score * 100:.0f}%"
    extra = ""
    if s.get("infra_error"):
        extra += f" +{s['infra_error']} infra"
    if s.get("skipped"):
        extra += f" +{s['skipped']} skip"
    return f"{s['pass']}/{s['pass'] + s['fail']} {pct}{extra}"


def _flag_text(f: dict) -> str:
    if f["type"] == "layer_score_drop":
        return (
            f"REGRESSION layer {f['layer']}: {f['from'] * 100:.0f}% -> "
            f"{f['to'] * 100:.0f}% (vs {f['previous_run']})"
        )
    return f"REGRESSION {f['test']}: PASS -> {f['to']} (vs {f['previous_run']})"


def _all_layers(recs: list[dict]) -> list[str]:
    names = set()
    for r in recs:
        names.update(r.get("layers", {}).keys())
    return sorted(names)


def render_markdown(recs: list[dict], flags: dict[str, list[dict]]) -> str:
    layers = _all_layers(recs)
    lines = [
        "# Totto test history (trend)",
        "",
        "Generated by `python -m totto_suite trend` from `evals/history/runs/*.json`.",
        "One row per recorded run, ordered by point time (time of the agent"
        " content: commit time, live app update time, or original result time).",
        "Layer cells: `passed/decided score` (score = PASS/(PASS+FAIL));"
        " INFRA_ERROR is never counted as pass or fail.",
        "",
    ]
    header = [
        "#",
        "point time",
        "mode",
        "imported",
        "agent commit + path",
        "CXAS version",
        "model",
        "rationale",
        *layers,
        "INFRA_ERROR",
        "regressions",
    ]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))
    for i, r in enumerate(recs, 1):
        agent = r["agent"]
        dirty = " (dirty)" if agent.get("dirty") else ""
        row = [
            str(i),
            r["point_time"],
            r["mode"],
            "yes" if r["imported"] else "no",
            f"`{_short(agent['commit'])}` {agent['path']}{dirty}",
            _version_cell(r),
            r["cxas"].get("model") or "?",
            (r["rationale"] or "").replace("|", "\\|").replace("\n", " "),
        ]
        for layer in layers:
            s = r["layers"].get(layer)
            row.append(_layer_cell(s) if s else "")
        row.append(str(r["infra_errors"]["count"]))
        run_flags = flags.get(r["run_id"], [])
        row.append(
            "<br>".join(_flag_text(f) for f in run_flags) if run_flags else "none"
        )
        lines.append("| " + " | ".join(row) + " |")
    total_flags = sum(len(v) for v in flags.values())
    lines += [
        "",
        f"Points: {len(recs)}. Regression flags: {total_flags}.",
        "",
        "Run ids (same order): "
        + ", ".join(f"{i}=`{r['run_id']}`" for i, r in enumerate(recs, 1)),
        "",
    ]
    return "\n".join(lines)


def _svg_chart(recs: list[dict], layers: list[str]) -> str:
    points = [r for r in recs if r.get("layers")]
    if not points or not layers:
        return "<p>No per-layer scores recorded yet.</p>"
    width, height, pad = 720, 220, 30
    n = len(recs)
    palette = [
        "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd",
        "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf",
    ]

    def x(i: int) -> float:
        return pad + (width - 2 * pad) * (i / max(n - 1, 1))

    def y(score: float) -> float:
        return height - pad - (height - 2 * pad) * score

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height + 20 * len(layers)}">',
        f'<rect x="0" y="0" width="{width}" height="{height}" fill="#fafafa" stroke="#ccc"/>',
    ]
    for frac in (0, 0.5, 1):
        parts.append(
            f'<line x1="{pad}" x2="{width - pad}" y1="{y(frac)}" y2="{y(frac)}" stroke="#ddd"/>'
            f'<text x="2" y="{y(frac) + 4}" font-size="10">{int(frac * 100)}%</text>'
        )
    for li, layer in enumerate(layers):
        color = palette[li % len(palette)]
        coords = [
            (x(i), y(r["layers"][layer]["score"]))
            for i, r in enumerate(recs)
            if layer in r.get("layers", {}) and r["layers"][layer].get("score") is not None
        ]
        if len(coords) > 1:
            path = " ".join(f"{cx:.1f},{cy:.1f}" for cx, cy in coords)
            parts.append(
                f'<polyline points="{path}" fill="none" stroke="{color}" stroke-width="2"/>'
            )
        for cx, cy in coords:
            parts.append(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="3" fill="{color}"/>')
        ly = height + 15 + 20 * li
        parts.append(
            f'<rect x="{pad}" y="{ly - 9}" width="10" height="10" fill="{color}"/>'
            f'<text x="{pad + 15}" y="{ly}" font-size="12">{html.escape(layer)}</text>'
        )
    parts.append("</svg>")
    return "".join(parts)


def render_html(recs: list[dict], flags: dict[str, list[dict]]) -> str:
    layers = _all_layers(recs)
    esc = html.escape
    head = [
        "#", "point time", "mode", "imported", "agent commit + path",
        "CXAS version", "model", "rationale", *layers, "INFRA_ERROR", "regressions",
    ]
    rows = []
    for i, r in enumerate(recs, 1):
        agent = r["agent"]
        run_flags = flags.get(r["run_id"], [])
        cells = [
            str(i),
            esc(r["point_time"]),
            esc(r["mode"]),
            "yes" if r["imported"] else "no",
            f"<code>{esc(_short(agent['commit']))}</code> {esc(agent['path'])}"
            + (" <b>(dirty)</b>" if agent.get("dirty") else ""),
            esc(_version_cell(r)),
            esc(r["cxas"].get("model") or "?"),
            esc(r["rationale"] or ""),
        ]
        for layer in layers:
            s = r["layers"].get(layer)
            cells.append(esc(_layer_cell(s)) if s else "")
        cells.append(str(r["infra_errors"]["count"]))
        cells.append(
            "<br>".join(f'<span class="reg">{esc(_flag_text(f))}</span>' for f in run_flags)
            if run_flags
            else "none"
        )
        cls = ' class="regrow"' if run_flags else ""
        rows.append(
            f"<tr{cls} title=\"{esc(r['run_id'])}\">"
            + "".join(f"<td>{c}</td>" for c in cells)
            + "</tr>"
        )
    total_flags = sum(len(v) for v in flags.values())
    return (
        "<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">"
        "<title>Totto test history</title><style>"
        "body{font-family:sans-serif;margin:1.5em}"
        "table{border-collapse:collapse;font-size:13px}"
        "td,th{border:1px solid #bbb;padding:4px 6px;vertical-align:top}"
        "th{background:#eee}.reg{color:#b00;font-weight:bold}"
        "tr.regrow{background:#fff0f0}"
        "</style></head><body>"
        "<h1>Totto test history</h1>"
        "<p>One row per recorded run, ordered by point time (time of the agent"
        " content). Layer cells: passed/decided and score = PASS/(PASS+FAIL);"
        " INFRA_ERROR is its own category. Regressions: a layer score drop or a"
        " test that passed at its previous point and now fails.</p>"
        f"<p>Points: {len(recs)}. Regression flags: {total_flags}.</p>"
        + _svg_chart(recs, layers)
        + "<table><tr>"
        + "".join(f"<th>{esc(h)}</th>" for h in head)
        + "</tr>"
        + "".join(rows)
        + "</table></body></html>\n"
    )


def generate(
    runs_dir: Path | None = None,
    md_path: Path | None = None,
    html_path: Path | None = None,
    index_path: Path | None = None,
) -> dict:
    """Rebuilds index.json, TREND.md and trend.html from the run records."""
    recs = records.load_all(runs_dir)
    flags = compute_regressions(recs)
    md_path = Path(md_path or config.TREND_MD_PATH)
    html_path = Path(html_path or config.TREND_HTML_PATH)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(render_markdown(recs, flags), encoding="utf-8")
    html_path.write_text(render_html(recs, flags), encoding="utf-8")
    idx = records.write_index(recs, index_path=index_path, runs_dir=runs_dir)
    return {
        "points": len(recs),
        "regressions": sum(len(v) for v in flags.values()),
        "flags": flags,
        "paths": [str(md_path), str(html_path), str(idx)],
    }
